export const INPUT_TYPE = {
  DEFAULT: 'DEFAULT',
  CONTACT_SIMPLE: 'CONTACT_SIMPLE',
};

export const RESPONSE_TYPE = {
  TEXT_RESPONSE: 'TEXT_RESPONSE',
  LLM_RESPONSE: 'LLM_RESPONSE',
  TEXT_WITH_IMAGE: 'TEXT_WITH_IMAGE',
  SKILLS: 'SKILLS',
  TIMELINE: 'TIMELINE',
  EVENT: 'EVENT',
  USER_MESSAGE: 'USER_MESSAGE',
  IMAGE: 'IMAGE',
  FILE: 'FILE',
  RESTART: 'RESTART',
};

export const USER_MESSAGE_TYPE = {
  INITIATE: 'INITIATE',
  DEFAULT: 'DEFAULT',
  CONTACT_SIMPLE_SEND: 'CONTACT_SIMPLE_SEND',
  CONTACT_SIMPLE_CANCEL: 'CONTACT_SIMPLE_CANCEL',
};

export const DEFAULT_INPUT_MAX_LENGTH = 256;
export const CONTACT_INPUT_MAX_LENGTH = 256;
export const CONTACT_BODY_MAX_LENGTH = 8192;
export const ORIGIN_QUERY_PARAM = 'o';
export const ORIGIN_QUERY_MAX_LENGTH = 256;

export const MAX_META_BALL = 40;

export const DISABLED_INPUT_TIMEOUT = 8000;
